In [2]:
import pandas as pd

In [5]:
df1 = pd.read_csv('Post_Regex_Data.csv')
df2 = pd.read_csv('final.csv')

In [6]:
df1.sort_values(by='Lawyer Names', inplace=True, ignore_index=True)
df1

,Rating,Jurisdiction,Charges,Days_of_disposal,City,Years_of_Experience,Type_of_Lawyer,Languages,Pro_bono,Lawyer Names,Lawfirms,Demography
0,5.0,Supreme Court,489,107.0,['Chennai'],21,"['Constitutional', 'Immigration', 'Constitutio...","['Marathi', 'Hindi']",no,Aaina Ganesan,['Tara Inc'],Small Businesses.
1,4.0,District Court,70,91.0,['Mumbai'],15,"['Human Rights', 'Labor', 'Corporate']","['Kannada', 'Hindi', 'Odia']",yes,Aaina Gopal,"['Issac', 'Vaidya', 'Varma']",Small Businesses.
2,4.0,District Court,282,106.0,['Mumbai'],22,"['Medical', 'Immigration', 'Civil']","['Bengali', 'Urdu']",yes,Aaina Kanda,['Anne-Srinivasan'],Individuals.
3,1.0,Specialized Court,490,102.0,['Mumbai'],5,"['Consumer Protection', 'Environmental', 'Envi...","['Punjabi', 'Bengali', 'Assamese']",yes,Aaina Kaul,['Amble Ltd'],Individuals.
4,1.0,Specialized Court,441,85.0,['Hyderabad'],7,"['Corporate', 'Criminal', 'Labor']","['Telugu', 'Urdu', 'Punjabi']",no,Aaina Kurian,['Mall-Tiwari'],Individuals.
...,...,...,...,...,...,...,...,...,...,...,...,...
1994,2.0,Specialized Court,81,94.0,['Chennai'],18,"['Family', 'Constitutional', 'Consumer Protect...","['Telugu', 'Urdu', 'Tamil']",yes,Zoya Shan,['Zacharia PLC'],Large Corporations.
1995,4.0,High Court,440,103.0,['Hyderabad'],7,"['Immigration', 'Criminal', 'Media and Enterta...","['Telugu', 'Urdu']",yes,Zoya Sood,['Grover PLC'],Small Businesses.
1996,1.0,Specialized Court,464,107.0,['Bangalore'],10,"['Family', 'Labor', 'Banking and Finance']","['Bengali', 'Telugu', 'Urdu']",no,Zoya Subramaniam,"['Goel', 'Bhatia', 'M', 'al']",Individuals.
1997,3.0,Supreme Court,427,85.0,['Chennai'],15,"['Intellectual Property', 'Labor', 'Environmen...","['Gujarati', 'Marathi', 'Odia']",no,Zoya Verma,"['Konda', 'Sons']",Individuals.
1998,3.0,Specialized Court,495,101.0,['Delhi'],29,"['Real Estate', 'Media and Entertainment', 'Ci...","['Gujarati', 'Odia', 'Hindi']",yes,Zoya Wali,"['Sarraf', 'Kadakia', 'Tella']",Individuals.

In [7]:
df1['Gender'] = df2['Gender']
df1

,Rating,Jurisdiction,Charges,Days_of_disposal,City,Years_of_Experience,Type_of_Lawyer,Languages,Pro_bono,Lawyer Names,Lawfirms,Demography,Gender
0,5.0,Supreme Court,489,107.0,['Chennai'],21,"['Constitutional', 'Immigration', 'Constitutio...","['Marathi', 'Hindi']",no,Aaina Ganesan,['Tara Inc'],Small Businesses.,Female
1,4.0,District Court,70,91.0,['Mumbai'],15,"['Human Rights', 'Labor', 'Corporate']","['Kannada', 'Hindi', 'Odia']",yes,Aaina Gopal,"['Issac', 'Vaidya', 'Varma']",Small Businesses.,Female
2,4.0,District Court,282,106.0,['Mumbai'],22,"['Medical', 'Immigration', 'Civil']","['Bengali', 'Urdu']",yes,Aaina Kanda,['Anne-Srinivasan'],Individuals.,Female
3,1.0,Specialized Court,490,102.0,['Mumbai'],5,"['Consumer Protection', 'Environmental', 'Envi...","['Punjabi', 'Bengali', 'Assamese']",yes,Aaina Kaul,['Amble Ltd'],Individuals.,Female
4,1.0,Specialized Court,441,85.0,['Hyderabad'],7,"['Corporate', 'Criminal', 'Labor']","['Telugu', 'Urdu', 'Punjabi']",no,Aaina Kurian,['Mall-Tiwari'],Individuals.,Female
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1994,2.0,Specialized Court,81,94.0,['Chennai'],18,"['Family', 'Constitutional', 'Consumer Protect...","['Telugu', 'Urdu', 'Tamil']",yes,Zoya Shan,['Zacharia PLC'],Large Corporations.,Female
1995,4.0,High Court,440,103.0,['Hyderabad'],7,"['Immigration', 'Criminal', 'Media and Enterta...","['Telugu', 'Urdu']",yes,Zoya Sood,['Grover PLC'],Small Businesses.,Female
1996,1.0,Specialized Court,464,107.0,['Bangalore'],10,"['Family', 'Labor', 'Banking and Finance']","['Bengali', 'Telugu', 'Urdu']",no,Zoya Subramaniam,"['Goel', 'Bhatia', 'M', 'al']",Individuals.,Female
1997,3.0,Supreme Court,427,85.0,['Chennai'],15,"['Intellectual Property', 'Labor', 'Environmen...","['Gujarati', 'Marathi', 'Odia']",no,Zoya Verma,"['Konda', 'Sons']",Individuals.,Female
1998,3.0,Specialized Court,495,101.0,['Delhi'],29,"['Real Estate', 'Media and Entertainment', 'Ci...","['Gujarati', 'Odia', 'Hindi']",yes,Zoya Wali,"['Sarraf', 'Kadakia', 'Tella']",Individuals.,Female

In [ ]:
df1.to_csv('FINALdataset.csv')