In [43]:
import requests
import pandas as pd

In [44]:
data = pd.read_csv(r"C:\Users\a21ma\OneDrive\Desktop\Datahack\DataHack_2_Tensionflow\no_duplicates.csv")
data.drop('Unnamed: 0', axis=1, inplace=True)
data

   First_Name
0       Rania
1   Vardaniya
2     Aaryahi
3      Suhana
4       Anahi
5      Shayak
6       Ivana
7      Stuvan
8       Aaina
9       Rasha
10    Nirvaan
11    Indrans
12     Farhan
13      Abram
14    Mamooty
15       Emir
16     Kismat
17  Dharmajan
18     Ehsaan
19     Nehmat
20     Dhanuk
21   Parinaaz
22       Siya
23    Samaira
24      Seher
25    Shanaya
26   Neelofar
27      Shalv
28       Ryan
29     Taimur

In [45]:
name = []
name = [data for data in data['First_Name']]
gender = []

In [46]:
# Check if the request was successful (status code 200)
if response.status_code == 200:
    # Parse the JSON respons
    for i in range(len(name)):
        # Define the API endpoint URL with the name you want to query
        api_url = f"https://api.genderize.io?name={name[i]}"

        # Send an HTTP GET request to the API
        response = requests.get(api_url)
        gen = response.json().get("gender", "Unknown")
        gender.append(gen)
        probability = response.json().get("probability", 0.0)
        print(f"Name: {name[i]}")
        print(f"Predicted Gender: {gen}")
        print(f"Probability: {probability}")
    # Extract gender and probability from the response
    
    
    
else:
    print(f"Failed to retrieve data. Status code: {response.status_code}")

Name: Rania
Predicted Gender: female
Probability: 0.99
Name: Vardaniya
Predicted Gender: None
Probability: 0.0
Name: Aaryahi
Predicted Gender: None
Probability: 0.0
Name: Suhana
Predicted Gender: female
Probability: 1.0
Name: Anahi
Predicted Gender: female
Probability: 1.0
Name: Shayak
Predicted Gender: male
Probability: 1.0
Name: Ivana
Predicted Gender: female
Probability: 1.0
Name: Stuvan
Predicted Gender: None
Probability: 0.0
Name: Aaina
Predicted Gender: female
Probability: 0.95
Name: Rasha
Predicted Gender: female
Probability: 0.95
Name: Nirvaan
Predicted Gender: male
Probability: 1.0
Name: Indrans
Predicted Gender: None
Probability: 0.0
Name: Farhan
Predicted Gender: male
Probability: 1.0
Name: Abram
Predicted Gender: male
Probability: 1.0
Name: Mamooty
Predicted Gender: male
Probability: 1.0
Name: Emir
Predicted Gender: male
Probability: 0.99
Name: Kismat
Predicted Gender: male
Probability: 0.65
Name: Dharmajan
Predicted Gender: male
Probability: 1.0
Name: Ehsaan
Predicted Gender: male
Probability: 0.98
Name: Nehmat
Predicted Gender: female
Probability: 0.75
Name: Dhanuk
Predicted Gender: male
Probability: 1.0
Name: Parinaaz
Predicted Gender: None
Probability: 0.0
Name: Siya
Predicted Gender: female
Probability: 0.88
Name: Samaira
Predicted Gender: female
Probability: 1.0
Name: Seher
Predicted Gender: female
Probability: 0.98
Name: Shanaya
Predicted Gender: female
Probability: 1.0
Name: Neelofar
Predicted Gender: female
Probability: 1.0
Name: Shalv
Predicted Gender: male
Probability: 1.0
Name: Ryan
Predicted Gender: male
Probability: 1.0
Name: Taimur
Predicted Gender: male
Probability: 1.0

In [47]:
print(gender)

['female', None, None, 'female', 'female', 'male', 'female', None, 'female', 'female', 'male', None, 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'female', 'male', None, 'female', 'female', 'female', 'female', 'female', 'male', 'male', 'male']

In [49]:
data['Gender'] = gender
data
data.to_csv(r"C:\Users\a21ma\OneDrive\Desktop\Datahack\DataHack_2_Tensionflow\no_duplicates_after_api.csv")